insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(101,'SSNA','John',11111,'Approved' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(102,'CCAP','davi',22222,'Terminated' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(103,'KW','brusly',33333,'Denained' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(104,'QHP','tom',44444,'Approved' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(105,'SSNA','jom',55555,'Approved' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(106,'ABC','cat',66666,'Denaied' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(107,'CCAP','mat',77777,'Terminated' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(108,'QHP','charl',88888,'Approved' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(109,'SSNA','chats',99999,'Cansseld' );

insert into INSURANCE_PLANS (PLAN_ID, PLAN_NAME, HOLDER_NAME, HOLDER_SSN, PLAN_STATUS) values(110,'KW','duds',111110,'InvalidDetails' );

